<?xml version="1.0" encoding="windows-1252" standalone="yes"?>

<!DOCTYPE FILMS [
        <!ELEMENT FILMS (Film)* >
        <!ELEMENT Film (Titre, (Realisateur)+, (Scenario)*, Genre, Pays, Duree, Resume, (Acteurs)*, (Palmares)*,
                (Sortie)?, (Image)*, (Montage)*, (Musique)*, (Producteur)+, Distributeur, (Critique)*)>
        <!ELEMENT Realisateur  (Nom, Prenom)>
        <!ELEMENT Scenario     (Nom, Prenom)>
        <!ELEMENT Image        (Nom, Prenom)>
        <!ELEMENT Acteur       (Nom, (Prenom)?)>
        <!ELEMENT Montage      (Nom, Prenom)>
        <!ELEMENT Acteurs      (Acteur)+ >
        <!ELEMENT Critique     (Media, Auteur, (Note)?, (Titre)?, Texte) >
        <!ELEMENT Resume       ((Titre)?, Texte) >
        <!ELEMENT Genre        (#PCDATA) >
        <!ELEMENT Note         (#PCDATA) >
        <!ELEMENT Media        (#PCDATA) >
        <!ELEMENT Auteur       (#PCDATA) >
        <!ELEMENT Texte        (#PCDATA) >
        <!ELEMENT Pays         (#PCDATA) >
        <!ELEMENT Sortie       (#PCDATA) >
        <!ELEMENT Palmares     (#PCDATA) >
        <!ELEMENT Distributeur (#PCDATA) >
        <!ELEMENT Producteur   (#PCDATA) >
        <!ELEMENT Titre        (#PCDATA) >
        <!ELEMENT Duree        (#PCDATA) >
        <!ELEMENT Nom          (#PCDATA) >
        <!ELEMENT Prenom       (#PCDATA) >
        <!ELEMENT Musique      (#PCDATA) >

        <!ATTLIST Film
                ID              ID #REQUIRED
                Langue (fr|uk|vo)  #REQUIRED
                Affiche          CDATA "none">
        <!ATTLIST Realisateur
                ID                CDATA #REQUIRED>

        <!ATTLIST Acteur
                ID              ID #REQUIRED>
        ]>

<FILMS>
    <Film ID="f01" Affiche="http://www.homme-moderne.org/enfinpris/images/affiche.gif" Langue="fr">
        <Titre>Enfin pris ?</Titre>
        <Realisateur ID="r01">
            <Nom>Carles</Nom>
            <Prenom>Pierre</Prenom>
        </Realisateur>
        <Genre>Documentaire</Genre>
        <Pays>France</Pays>
        <Duree>1h30</Duree>
        <Resume>
            <Titre>Daniel Schneidermann dans le viseur du franc-tireur Pierre Carles.</Titre>
            <Texte>
                Ce nouveau film opère une synthèse. Il part de Bourdieu, coupant à
                l'éloge funèbre (le sociologue est mort en janvier dernier) pour mieux
                se fixer sur... Daniel Schneidermann. Le producteur-animateur d'Arrêt
                sur images avait, à la suite des grèves de l'hiver 1995, convié
                Bourdieu face à un panel de ténors cathodiques - Durand et surtout
                Cavada ne sortent pas grandis des extraits rediffusés. Bourdieu,
                auteur du pamphlet Sur la télévision, avait ensuite boudé. On voit
                Carles, en 1997, titiller son vieux copain Schneidermann en lui
                proposant de réinviter Bourdieu. Schneidermann rit jaune. Quelques
                années auparavant, Carles et lui avaient un projet commun de
                documentaire "animalier" sur le comportement des élites. L'affaire fit
                flop. Leurs chemins divergeant, l'un, arrivé, s'est retrouvé dans le
                collimateur de l'autre, éternel franc-tireur.

                On n'est jamais plus critique et sévère qu'avec celui qu'on aurait pu
                devenir. Carles assume tellement sa fixette sur Schneidermann qu'il en
                vient à se mettre en scène lui-même allongé sur le divan d'un psy - un
                de ses anciens profs. Ce papy Freud au perpétuel sourire à poil blanc
                distille d'une voix aiguë son fluet diagnostic. Sa présence comique
                est d'un effet irrésistible, on n'est pas loin de Woody Allen ou de
                Nanni Moretti. Cette longue séquence donne aussi la clé du film ­ et,
                à rebours, des précédents : le petit Caméscope où défilent les images
                de l'autre (Schneidermann), censées prouver sa schizophrénie, est un
                miroir. Pierre Carles finit par rire comme un gosse, et nous avec, de
                s'y voir au fond en quête de lui-même. Chez celui qui s'échappe, il y
                a toujours le secret désir d'être pris.
            </Texte>
        </Resume>
        <Acteurs>
            <Acteur ID="a01">
                <Nom>Carles</Nom>
                <Prenom>Pierre</Prenom>
            </Acteur>
            <Acteur ID="a02">
                <Nom>Bourdieu</Nom>
                <Prenom>Pierre</Prenom>
            </Acteur>
            <Acteur ID="a03">
                <Nom>Schneidermann</Nom>
                <Prenom>Daniel</Prenom>
            </Acteur>
        </Acteurs>
        <Image>
            <Nom>Carles</Nom>
            <Prenom>Pierre</Prenom>
        </Image>
        <Montage>
            <Nom>Bour</Nom>
            <Prenom>Gilles</Prenom>
        </Montage>
        <Montage>
            <Nom>Painchault</Nom>
            <Prenom>Claire</Prenom>
        </Montage>
        <Montage>
            <Nom>Sasia</Nom>
            <Prenom>Bernard</Prenom>
        </Montage>
        <Musique>Jay-Jay Johanson</Musique>
        <Producteur>C-P Productions</Producteur>
        <Distributeur>Cara M</Distributeur>
        <Critique>
            <Media>Telerama</Media>
            <Auteur>François Gorin</Auteur>
            <Texte>Ce film, il faudra le chercher, mais sa très modeste distribution
                cache une estimable ambition : être vu. Pour ceux qui auraient raté
                les épisodes précédents, Carles est ce pierrot lunaire aperçu à la
                télé chez Rapp ou Dechavanne, sitôt viré qu'il était engagé, puis
                dûment étiqueté "électron libre du PAF", manière comme une autre
                d'être enfermé. Doux paradoxe, le studieux potache a trouvé une forme
                de salut au cinéma, d'où il nargue, fort d'un fan-club cloué au
                fauteuil par ses tours de pince-sans-rire, la mère-télé indigne,
                unique objet de son ressentiment maniaque. Pas vu pas pris traquait
                les mensonges pas toujours pieux de certains ténors cathodiques. La
                sociologie est un sport de combat hissait Pierre Bourdieu sur le
                piédestal d'une admiration après tout légitime.
            </Texte>
        </Critique>
        <Critique>
            <Media>Le Monde</Media>
            <Auteur>Isabelle Regnier</Auteur>
            <Texte>Enfin pris ? est le nouvel épisode de la croisade du trublion Pierre
                Carles contre la télévision. Homme de convictions, Pierre Carles
                défend depuis des années, avec un acharnement jamais démenti, l'idée
                selon laquelle le petit écran est la vitrine du pouvoir politique,
                donc réfractaire par définition à toute forme de
                subversion. Soit. Après s'en être pris aux journalistes de télévision
                dans Pas vu à la télé (1994) et Pas vu pas pris (1998), il s'attaque
                aujourd'hui aux émissions de critique du petit écran.

                Fidèle à une méthode dont il assume la malhonnêteté (seule stratégie
                possible face aux représentants d'un organe ontologiquement corrompu,
                soutenait-il dans Pas vu pas pris), il s'arroge la parole d'autrui par
                l'enregistrement de conversations téléphoniques et autres messages sur
                répondeur, auxquels il adjoint ses commentaires. Sans avoir le moindre
                droit de réponse, ses interlocuteurs font les frais de ce dispositif
                non démonstratif, exclusivement destiné à servir son opinion. Dans
                Enfin pris ?, Daniel Schneidermann, présentateur de l'émission "Arrêt
                sur images", chroniqueur au Monde et ancien collaborateur de Pierre
                Carles (ils ont coréalisé un documentaire sur la vie des élites en
                1992), est pris pour cible.
            </Texte>
        </Critique>
    </Film>
    <Film ID="f02" Langue="uk"
          Affiche="https://m.media-amazon.com/images/M/MV5BMzkxMjI4MjYtNjYzMC00ZTE1LWJlNjAtNWIyYzU3Njc3ODRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg">
        <Titre>11'09''01</Titre>
        <Realisateur ID="r02">
            <Nom>Makhmalbaf</Nom>
            <Prenom>Samira</Prenom>
        </Realisateur>
        <Realisateur ID="r03">
            <Nom>Lelouch</Nom>
            <Prenom>Claude</Prenom>
        </Realisateur>
        <Realisateur ID="r04">
            <Nom>Chahine</Nom>
            <Prenom>Youssef</Prenom>
        </Realisateur>
        <Realisateur ID="r05">
            <Nom>Tanovic</Nom>
            <Prenom>Danis</Prenom>
        </Realisateur>
        <Realisateur ID="r06">
            <Nom>Ouedraogo</Nom>
            <Prenom>Idrissa</Prenom>
        </Realisateur>
        <Realisateur ID="r07">
            <Nom>Loach</Nom>
            <Prenom>Ken</Prenom>
        </Realisateur>
        <Realisateur ID="r08">
            <Nom>Iñárritu</Nom>
            <Prenom>Alejandro Gonzáles</Prenom>
        </Realisateur>
        <Realisateur ID="r09">
            <Nom>Gitai</Nom>
            <Prenom>Amos</Prenom>
        </Realisateur>
        <Realisateur ID="r10">
            <Nom>Nair</Nom>
            <Prenom>Mira</Prenom>
        </Realisateur>
        <Realisateur ID="r11">
            <Nom>Penn</Nom>
            <Prenom>Sean</Prenom>
        </Realisateur>
        <Realisateur ID="r12">
            <Nom>Imamura</Nom>
            <Prenom>Shohei</Prenom>
        </Realisateur>
        <Genre>Retour sur actualité</Genre>
        <Pays>France</Pays>
        <Duree>2h10</Duree>
        <Resume>
            <Texte>
                Onze cinéastes de renom invités à exprimer en onze minutes leur
                manière de se souvenir, un ans après, du drame qui frappa l?Amérique
                le 11/09/2001. Un patchwork de onze regards aux références politiques,
                religieuses, culturelles différentes, onze styles venus de tous les
                points du globe comme le rappelle l?introduction de chaque court
                métrage.
            </Texte>
        </Resume>
        <Musique>Alexandre Desplat</Musique>
        <Producteur>Galaté Films-StudioCanal</Producteur>
        <Distributeur>Bac Distribution</Distributeur>
        <Critique>
            <Media>Télérama</Media>
            <Auteur>Jean-Claude Loiseau</Auteur>
            <Texte>C'est le genre d'idée saugrenue qui avait toute chance de tourner au
                fiasco. Mettre une pléiade de cinéastes au défi d'imaginer les images
                qui "répondraient" à celles, indélébiles, des tours du World Trade
                Center frappées de plein fouet avant de s'effondrer ; à celles, encore
                plus hallucinantes, des corps qui n'en finissent pas de tomber dans le
                vide... Forcément, onze films courts et disparates mis bout à bout ne
                font pas un film cohérent. Si l'on oublie le "formatage" gadget ­
                chaque film devait durer 11 minutes 9 secondes et une image (!) ­ la
                diversité est, en soi, une forme de réussite. Il y a ces éclats de
                liberté qui s'imposent, dans le spectacle ou la sobriété. Avec le film
                de Danis Tanovic, on est soudain touché de plein fouet par la douleur
                digne d'un cortège de femmes bosniaques, habituées à manifester en
                silence le 11 de chaque mois pour leurs disparus. Les petits réfugiés
                afghans, filmés par Samira Makhmalbaf dans une classe improvisée de la
                campagne iranienne, ont une vision du monde qui déjoue l'attente d'un
                spectateur occidental.

                Prendre du recul, dépasser le choc émotionnel des images du 11
                septembre. Mais comment ? La fable chaleureuse et ironique d'Idrissa
                Ouedraogo, avec ses gosses qui traquent Ben Laden sur le marché de
                Ouagadougou, est aux antipodes du rappel calme mais implacable que Ken
                Loach fait d'un autre 11 septembre : ce jour de 1973 où les avions
                bombardaient le palais présidentiel chilien, tuant Allende et lançant
                du même coup une longue et sanglante chasse aux sorcières. En un
                plan-séquence virtuose, Amos Gitai, de son côté, a imaginé de
                confronter l'attentat de New York à celui qui se produit au même
                moment à Tel Aviv. Ici, la belle idée de cinéma est le tremplin d'une
                réflexion limpide. Mais rien n'est aussi percutant, dans cette
                mosaïque hétéroclite, que l'essai limite du Mexicain Alejandro
                Gonzáles Iñárritu. Un écran noir avec juste des flashes, de loin en
                loin, sur des corps en chute libre, et une bande-son saisissante, des
                cris, des chants psalmodiés, un brouillard de voix éperdues : le
                cinéaste ravive l'horreur de manière littéralement inouïe.

                Alors on oubliera les ratés, et le coup de colère maladroitement
                antiaméricain de Youssef Chahine, qui a suffi à créer une polémique.
                Dans 11'9"01, la majorité des cinéastes ont choisi de confronter la
                tragédie vécue par les Américains aux souffrances, grandes et petites,
                qui submergent leur propre peuple. Un contrepoint utile. Et à
                discuter.
            </Texte>
        </Critique>
        <Critique>
            <Media>Pro-fil</Media>
            <Auteur>Jean Domon</Auteur>
            <Texte>On aurait pu craindre ce genre de films-à-sketches que l?on connaît
                bien, et qui sont plus ou moins réussis. Cet ensemble est au contraire
                la saisissante illustration de ce que peut être aujourd?hui le cinéma
                dans sa totale liberté d?invention à être le témoin de notre
                temps. Onze films qu?il faut absolument analyser et faire jouer entre
                eux, tant ils diffractent à l?infini des images et des messages qui
                dessinent un impressionnant portrait de notre planète inquiète et
                douloureuse. Car il y a d?autres 11 Septembre, de Srebenica (ah, les
                plans et les lumières de Tanovic !) à Santiago du Chili (terribles
                archives rassemblées par Ken Loach !) et tant d?autres qu?égrène cette
                hystérique journaliste en plein désarroi terroriste à Tel Aviv
                (étonnant plan séquence de Gitaï !).Des audaces d?écritures, sans
                paroles avec Lelouch ou sans images avec Inarritu, dénoncent l?
                incapacité d?une télévision réductioniste à nous introduire au c?ur du
                drame. Et Dieu dans tout ça ? demande le profilien soucieux . Les
                petits réfugiés afghans se demandent s?Il est capable de détruire les
                humains alors que leur institutrice tente vainement de leur faire
                observer une minute de silence à la mémoire de victimes pour eux si
                lointaines ( Bravo Samira !) .Le Mexicain, lui, qui nous maintient
                dans le noir et les cris d?affolement, ouvre sa prestation sur des
                litanies de prières et la referme sur cette phrase écrite en arabe :
                "Est ce que Dieu nous guide ou nous aveugle ? ". Quant aux dernières
                paroles de ces 130 minutes, c?est Imamura qui nous les offre à travers
                la formidable métaphore de cet ancien combattant de la guerre
                sino-japonaise devenu serpent : "il n'y a pas de guerre sainte".
            </Texte>
        </Critique>
    </Film>

    <Film ID="f03" Langue="vo" Affiche="https://members.loria.fr/YBoniface/html/xml/file/LastParty2000.jpg">
        <Titre>Last Party 2000</Titre>
        <Realisateur ID="r13">
            <Nom>Chaiklin</Nom>
            <Prenom>Rebecca</Prenom>
        </Realisateur>
        <Realisateur ID="r14">
            <Nom>Leitch</Nom>
            <Prenom>Donovan</Prenom>
        </Realisateur>
        <Genre>Documentaire</Genre>
        <Pays>Américain</Pays>
        <Duree>1h37</Duree>
        <Resume>
            <Texte>L'année 2000 fut une année critique pour le système démocratique
                américain. Après des élections présidentielles tirées par les
                cheveux, la Cour Supre^me tranche et donne le pouvoir au parti
                républicain. Un retournement sans précédent pour une Amérique
                régie depuis 8 ans par le parti démocrate. Last Party 2000 retrace
                ce moment unique.
            </Texte>
        </Resume>
        <Acteurs>
            <Acteur ID="a04">
                <Nom>Hoffman</Nom>
                <Prenom>Philip Seymour</Prenom>
            </Acteur>
            <Acteur ID="a05">
                <Nom>O'Donnell</Nom>
                <Prenom>Rosie</Prenom>
            </Acteur>
            <Acteur ID="a06">
                <Nom>Chomsky</Nom>
                <Prenom>Noam</Prenom>
            </Acteur>
            <Acteur ID="a07">
                <Nom>Moore</Nom>
                <Prenom>Michael</Prenom>
            </Acteur>
            <Acteur ID="a08">
                <Nom>Nader</Nom>
                <Prenom>Ralph</Prenom>
            </Acteur>
        </Acteurs>
        <Montage>
            <Nom>Hoffmann</Nom>
            <Prenom>Sabine</Prenom>
        </Montage>
        <Musique>Susan Jacobs</Musique>
        <Producteur>Dajota Group Ltd</Producteur>
        <Distributeur>ID Distribution.</Distributeur>
        <Critique>
            <Media>telerama</Media>
            <Auteur>Jean-Claude Loiseau</Auteur>
            <Texte>Et après un ubuesque décompte des voix, Bush fut élu. C'est bien tout
                ce qui reste d'une campagne qui fut, de bout en bout, d'une morne
                platitude. Un duo de documentaristes, lancé sur la piste des candidats
                dès les primaires, a assez vite compris qu'ils devraient prendre la
                tangente. Avec, pour poisson pilote, un (excellent) acteur, Philip
                Seymour Hoffman, Candide sceptique mais curieux, le film fait la
                politique buissonnière. Entre deux coups d'oeil pertinents ­ donc
                impertinents ­ sur le fonctionnement de la "machine" politique, les
                auteurs et Hoffman vont regarder ailleurs, engrangeant les interviews
                spontanées avec des étudiants, des artistes, des retraités,
                indifférents, désabusés, cyniques. Ou bien ce sont les activistes
                radicaux qu'on découvre aux abords des conventions (la démocrate comme
                la républicaine), tenant meetings effervescents ou affrontant les
                flics omniprésents, dans des séquen-ces-chocs rarement montrées par la
                télé.

                La sortie du film a été repoussée sine die pour cause de 11 septembre.
                Cela en affaiblit un peu la portée aujourd'hui, mais cette enquête de
                terrain menée à l'arraché, parfois brouillonne ­ trop de thèmes
                effleurés ­ est très tonique : on y voit que la vie palpite hors des
                sentiers balisés de la politique officielle. Et le tout est
                efficacement retravaillé au montage (choix musicaux "pointus" inclus)
                pour capter l'attention du public visé en priorité : celui des jeunes
                Américains que la politique fait fuir. Michael Moore, qui fait une
                apparition furtive dans le film, a fait des émules : Rebecca Chaiklin
                et Donovan Leitch ont, sinon la force de frappe, au moins la pugnacité
                de l'illustre modèle, et c'est plutôt une bonne nouvelle.
            </Texte>
        </Critique>
        <Critique>
            <Media>chronic'art</Media>
            <Auteur>Jean-Philippe Tessé</Auteur>
            <Note>3</Note>
            <Texte>Tourné tout au long de la campagne électorale américaine en 2000, Last
                party 2000 n?est pas tout à fait un retour sur la résistible ascension
                de George W.Bush vers la Maison Blanche, mais davantage un road movie
                politique au pays de l?Oncle Sam. On peut y voir, c?est déjà ça, un
                antidote revigorant à l?hystérie béate qui accompagne, depuis sa
                sortie, l?affreux Bowling for Columbine de Michael Moore. Moore,
                d?ailleurs, apparaît dans le film, pour une brève interview et le
                temps d?une séquence filmée lors d?un meeting de soutien à Ralph
                Nader, le candidat écologiste à la présidence (qui obtiendra 3% des
                voix, après s?être vu refuser le droit de débattre publiquement avec
                ses adversaires Bush et Gore). On le découvre en tribun efficace,
                c?est-à-dire un rôle enfin lavé de toutes les afféteries minaudeuses
                et hypocrites dont il infecte ses films. Dans Last party 2000, c?est
                Philip Seymour-Hoffman qui endosse le costume du candide en quête de
                réponses à ses préoccupations de citoyen électeur. Le comédien (vu
                chez Paul Thomas Anderson, Todd Solondz ou les frères Coen) avoue
                immédiatement ne rien connaître à la politique, n?avoir fait aucun
                effort pour remédier à cela jusqu?à présent, si ce n?est rejeter en
                bloc tous les dirigeants, considérés comme pourris et avides de
                pouvoir.

                La fraîcheur naïve de ses interrogations fait du film un documentaire
                inoffensif, mais il a au moins le mérite de nous épargner la vulgate
                pathétique de Moore. Candide, Seymour Hoffman l?est vraiment, à
                l?inverse de Moore qui feint de l?être et se place d?emblée dans une
                position sentimentalo-ricanante de condescendance et de
                fatuité. Accompagné par les réalisateurs, il prend son bâton de
                pèlerin pour un long périple à travers les Etats-Unis. Au programme :
                congrès républicains et démocrates en forme de pathétiques kermesses
                vulgaires où l?on se répète mot pour mot d?un camp à l?autre, et
                rencontres avec Noam Chomsky, Jesse Jackson et tout ce que l?Amérique
                compte de José Bové locaux, de courants alternatifs, d?associations de
                défense des démunis ou des minorités. Un portrait en creux d?un
                paysage politique récalcitrant aux discours lénifiants des deux grands
                partis, qui certes s?est exprimé plus fort que jamais lors de la
                campagne 2000, mais dont on a finalement beaucoup de mal à mesurer
                l?audience réelle. Le film ne propose guère plus qu?une suite
                d?interviews et de reportages live au coeur des manifestations (où
                l?on peut se rendre compte de l?effrayante brutalité de la police, qui
                tolère à peine la libre expression dans la rue) et des congrès des
                candidats, mais il le fait relativement bien.
            </Texte>
        </Critique>
    </Film>
    <Film ID="f04" Langue="uk" Affiche="https://www.les400coups.org/affiches/bigger/sweetsixteen.jpg">
        <Titre>Sweet Sixteen</Titre>
        <Realisateur ID="r07">
            <Nom>Loach</Nom>
            <Prenom>Ken</Prenom>
        </Realisateur>
        <Scenario>
            <Nom>Laverty</Nom>
            <Prenom>Paul</Prenom>
        </Scenario>
        <Genre>réalisme politique</Genre>
        <Pays>Britannique</Pays>
        <Duree>1h46</Duree>
        <Resume>
            <Texte>
                Dans quelques jours, Liam aura 16 ans. Sa mère, Jean, qui est en
                prison, doit être libérée à temps pour l'anniversaire de son
                fils. Liam compte bien saisir l'occasion pour que, cette fois enfin,
                tout se passe bien. Il rêve d'une famille comme il n'en a jamais eue
                et redoute l'influence de son grand-père, comme celle de Stan, le
                compagnon de Jean. Il veut un foyer, un endroit sûr pour sa mère, sa
                soeur Chantelle et lui-même.

                Encore faut-il trouver de l'argent et, pour un adolescent fauché, ce
                n'est pas une mince affaire. Avec ses copains, Liam enchaîne les
                combines mais, rapidement, les ennuis commencent. Liam sent bien que
                la situation devient grave et qu'il perd pied. Il faudrait partir mais
                peut-être est-il déjà trop tard.
            </Texte>
        </Resume>
        <Acteurs>
            <Acteur ID="a09">
                <Nom>Compston</Nom>
                <Prenom>Martin</Prenom>
            </Acteur>
            <Acteur ID="a10">
                <Nom>Ruane</Nom>
                <Prenom>William</Prenom>
            </Acteur>
            <Acteur ID="a11">
                <Nom>Fulton</Nom>
                <Prenom>Annmarie</Prenom>
            </Acteur>
            <Acteur ID="a12">
                <Nom>Abercromby</Nom>
                <Prenom>Michelle</Prenom>
            </Acteur>
        </Acteurs>
        <Palmares>meilleur scénario au 55ème Festival de Cannes</Palmares>
        <Image>
            <Nom>Ackroyd</Nom>
            <Prenom>Barry</Prenom>
        </Image>
        <Montage>
            <Nom>Morris</Nom>
            <Prenom>Jonathan</Prenom>
        </Montage>
        <Musique>George Fenton</Musique>
        <Producteur>Sixteen Films, Road Movie filmproduktion et Tornasol/Altafilm</Producteur>
        <Distributeur>Diaphana</Distributeur>
        <Critique>
            <Media>telerama</Media>
            <Auteur>Cécile Mury</Auteur>
            <Texte>Liam a bientôt 16 ans, une jolie caboche gouailleuse déjà marquée
                d'enfant trop vieux pour son âge et une famille dévastée. Maman en
                prison, beau-père dealer, minable et brutal, soeur à peine sortie de
                l'adolescence et déjà mère, qui tente de s'en sortir toute seule. Vif
                et futé, Liam est lui aussi obsédé par la reconquête d'un foyer, et
                surtout de cette mère flottante, absente, paumée, qui a tout lâché
                depuis longtemps. Cet amour inconditionnel pour une ombre de femme,
                cet oedipe mal taillé, trop grand, trop large, que le beau-père se
                charge de soigner à coups de poing, est au coeur du récit, moteur
                furieux et emballé d'une course éperdue, perdue d'avance. Pour sa
                mère, pour lui bricoler un avenir, lui trouver un peu d'argent, un
                toit, Liam est prêt à tout, même à se frotter aux truands du
                voisinage, même à risquer sa fragile existence.

                Ainsi réduite à ces quelques repères, l'histoire de Liam pourrait
                faire croire à un mauvais mélo, à une geste prolo d'une caricaturale
                noirceur. C'est tout le contraire. La chronique, intime et sociale,
                est douloureuse, violente, mais rythmée, souvent drôle, comme une
                chanson réaliste qui prendrait sa source et sa force dans chaque
                respiration. Prix du scénario à Cannes, le film renverse ironiquement
                l'idéologie américaine du "qui veut peut". Liam a le désir passionné
                de s'en sortir, de réussir, et toute cette belle énergie positive le
                mène droit à sa perte, dans les bras des trafiquants de drogue du
                quartier. Si le constat est amer, il ne tourne jamais à la
                démonstration pesante. Même coincée dans le béton, même au fond des
                foyers minables pour semi-délinquants juvéniles et au matin de mauvais
                coups qui laissent la gueule en sang, la vie reprend rageusement ses
                droits, dans un sourire, une insulte bien sentie en sabir écossais (le
                genre qui a valu au film une interdiction aux moins de 18 ans en
                Angleterre !) ou l'esquisse d'un geste tendre.

                Filmé, comme toujours chez Ken Loach, à distance respectueuse, dans un
                style quasi documentaire, l'adolescent mène sa quête désespérée avec
                une intensité rare. Dans ce procédé désormais familier, Martin
                Compston est la vraie originalité, la révélation, le principe
                d'étrangeté, trésor de naïveté et d'espoir scellé par le réel. Dents
                serrées, poings fermés, le jeune comédien sait donner une lumière, une
                vivacité exceptionnelles à son personnage. Gosse perdu, voyou, ni l'un
                ni l'autre, petit prince abîmé, il compose avec ses partenaires,
                mélange de comédiens professionnels et d'habitants du cru, comme il
                est de coutume chez Ken Loach, une réussite sobrement poignante.
            </Texte>
        </Critique>
        <Critique>
            <Media>Mr Cinema</Media>
            <Auteur>Jean-Luc Brunet</Auteur>
            <Note>4</Note>
            <Texte>Réalisateur prolifique, Ken Loach est aussi l'un de ceux qui montrent
                le mieux le prix à payer par les petits, les sans grades, pour garder
                ou obtenir leur liberté dans un monde de plus en plus impitoyable. En
                baisse de régime depuis quelques temps, le cinéaste fait un retour
                remarqué avec SWEET SIXTEEN, un film tendu et sans concessions, dans
                la veine de RAINING STONES ou RIFF RAFF. C'est Liam, jeune ado de 16
                ans, frondeur, courageux et auteur de 400 coups avec son pote Pinball,